### ISSUE TITLE
cannot lock on to certain transponders

### ISSUE THREAD

**Issue by psyborg55** [deeptho/neumodvb#8] opened 2022-01-25 17:44 UTC
trying to scan several transponders on different satellites brings no results. 
it appears the device is unable to lock, at least according to the fact that when i try to tune the chosen tp and monitor its signal properties in positioner window, there is only signal level, but no snr info obtained
i think this is the most likely related to device driver rather than the app itself, but your confirmation would be welcome
tps tried:
7e - 12549 v 2222
7e - 12680 h 3250
10e - 11482 v 2857
8w - 12620 v 890

altdvb tune them without problems.
thought maybe a problem with low sr, but then couldnt lock one with 14400 too

tried to implement blindscan routines from proprietary montage driver sources, and it appears fft scan is able to discover some transponders, but not everytime and not immediately.
sometimes it found tp within first 10 seconds, other times the driver looped for minutes before it detect tp.
in any case, when it saved the tp and tried to scan it i never got lock on to transponder. of course, all of this currently happens on kernel level only, if i get it to work then i will adapt routines to neumo apps

for now, i think main problem is the patched media driver that introduced some regression with m88ds3103 driver.

Logs included
[Download.zip](https://github.com/deeptho/neumodvb/files/7935912/Download.zip)

**Comment by deeptho** [comment] 2022-01-25 19:10
It is difficult to comment on this because each driver is very different. 

I would not consider 2222 a very small symbolrate, so unless there is a reception problem,
there is no reason why this should not lock. What is important: some lnbs have significant errors 
on  their local oscillator frequency. Sometimes up to 2Mhz. This means that you are basically tuning 2 Mhz away
from the correct frequency and if the transponders bandwidth is only a few Mhz, then that is enough to have no lock.

neumodvb compensates for this, but it can only do that if the driver reports the actually tuned frequency. I doubt this will 
be the case for any driver which I did not modify. So another thing to check is: what does the neumo LNB screen report
as LOF offsets? If for some reason it is misinterpreting bad or missing data, then neumoDVB itself could be the cause of the problem, but it is easy to spot on the LNB screen and could then be confirmed by tuning to a slightly lower or higher frequency.

I also remind you that your card's drivers rejects one of the tuning parameters. I do not know which one (but perhaps
using the latest drivers will reveal it). So that could also explain it.

If you can get an FFT spectrum in the montage drivers, then I would advise you to try and export it through my drivers. Peak detection can be done in user space (this is already included in the neumoDVB sources, but not used for stid135). Once that is working, then blindscanning will become easier as the peaks tend to give you at least the proper frequencies.

A last thing to check: it is easy to have a subscription to some other mux already running and not noticing. In that case
neumoDVB will silently fail, but /tmp/neumo.log will show that no suitable adapter could be found. Gradually, some 
error reporting to the gui will be introduced, starting with the next version.

Last: many drivers artificially limit symbol rate to 1Ms/s even if the chip can go lower. It is a matter of lowering the number
in the driver.

**Comment by psyborg55** [comment] 2022-01-25 21:28
I am using inverto black ultra, so it shouldnt be a problem. Even if it was, i noticed LOF offset is working (you can see it on screenshots in https://github.com/deeptho/neumodvb/issues/3) and different values have been observed there, like 20,36, 80,140 khz etc.
One question: should i expect FFT to give out symbolrate or its only purpose is to estimate the frequency?
About subscription to another service while trying to tune something: already noticed, when it happens i try to stop all the streams, and monitor my wall meter for power usage that goes to cards input, if it drops to 0 the tuning has stopped, if it stays at 2w i just restart the app.
There is artificial limitation of symbol rate in this driver to 1Ms/s but even with it the card still tunes 890ks/s stream

**Comment by deeptho** [comment] 2022-01-26 20:04
> One question: should i expect FFT to give out symbolrate or its only purpose is to estimate the frequency?
This can give an estimate of frequency and symbolrate, but the estimate is coarse and can be far off for weak signals.
It helps a lot with blindscan.

> About subscription to another service while trying to tune something: already noticed, when it happens i try to stop all the streams, and monitor my wall meter for power usage that goes to cards input, if it drops to 0 the tuning has stopped, if it stays at 2w i just restart the app.

For regular tuning, ctrl-X should do the trick. mux-scan currently seems to not stop in some cases, like when tuning fails. Also 0.8West has some specific problems as the muxes brodcast conflicting information.. I have made a few improvements but 
they have not been committed yet.

**Comment by psyborg55** [comment] 2022-01-27 21:30
Here is log while trying to scan 12680h, with updated media driver
[scan.zip](https://github.com/deeptho/neumodvb/files/7953908/scan.zip)

**Comment by psyborg55** [comment] 2022-01-28 20:20
some more info:

10e - 11482 v 2857
10e - 10836 v 3000

it tunes only signal level, but not SNR
It seems the timeout to tune these TPs should be increased
Altdvb on windows also takes quite a longer to scan them than most of the other TPs

3w - 12739 v 13172
similar as above, but setting FEC manually to 2/3 instead of auto helped to scan this mux

**Comment by deeptho** [comment] 2022-01-29 14:16
At least some of the problems you report are specific to your card. The 10E I will check later on my own card (stid135)

 The timeouts  are selected by the driver, but of course neumo does not wait forever. In fact it waits 15 seconds. 
That is already too long..

**Comment by psyborg55** [comment] 2022-01-30 14:28
Same thing as with SNR refresh, tvheadend+blindscan drivers tuned and scanned 12680 h 3250 immediately, even faster than altdvb

**Closed** 2022-02-10 13:38 UTC
